on: [push, pull_request]
name: lint
jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          tools: php-cs-fixer, cs2pr
          php-version: 7.4
      - run: php-cs-fixer fix --format=checkstyle --dry-run | cs2pr
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          tools: phpstan
          php-version: 7.4
      - run: composer install --ignore-platform-reqs
      - run: phpstan analyse src --level 5
